/**
 * SignDoc Comparison Script
 *
 * This script helps diagnose signature verification failures by comparing
 * the SignDoc generated by this app vs what the CLI produces.
 *
 * Usage:
 * 1. Generate an unsigned transaction using TX CLI:
 *    cored tx distribution withdraw-rewards <valoper-address> \
 *      --commission \
 *      --from <multisig-address> \
 *      --generate-only \
 *      --offline \
 *      --account-number <acctnum> \
 *      --sequence <seq> \
 *      --fees <fee> \
 *      --gas <gas> \
 *      -o json > cli-tx.json
 *
 * 2. Run this script with the CLI output and your app's transaction data
 */

import { makeSignDoc, serializeSignDoc, StdFee, AminoMsg } from "@cosmjs/amino";
import { sha256 } from "@cosmjs/crypto";
import { fromBase64, toBase64, fromHex, toHex } from "@cosmjs/encoding";
import { TxBody, AuthInfo, SignDoc as ProtoSignDoc } from "cosmjs-types/cosmos/tx/v1beta1/tx";
import { AminoTypes, createDefaultAminoConverters } from "@cosmjs/stargate";
import { createWasmAminoConverters } from "@cosmjs/cosmwasm-stargate";

// Helper to decode base64 protobuf bytes
function decodeBodyBytes(bodyBytesBase64: string): ReturnType<typeof TxBody.decode> {
  const bytes = fromBase64(bodyBytesBase64);
  return TxBody.decode(bytes);
}

function decodeAuthInfo(authInfoBytesBase64: string): ReturnType<typeof AuthInfo.decode> {
  const bytes = fromBase64(authInfoBytesBase64);
  return AuthInfo.decode(bytes);
}

interface CLITransaction {
  body: {
    messages: Array<{
      "@type": string;
      [key: string]: any;
    }>;
    memo: string;
    timeout_height: string;
    extension_options: any[];
    non_critical_extension_options: any[];
  };
  auth_info: {
    signer_infos: any[];
    fee: {
      amount: Array<{ denom: string; amount: string }>;
      gas_limit: string;
      payer: string;
      granter: string;
    };
  };
  signatures: string[];
}

interface AppTransaction {
  accountNumber: number;
  sequence: number;
  chainId: string;
  msgs: Array<{
    typeUrl: string;
    value: any;
  }>;
  fee: StdFee;
  memo: string;
}

export function compareTransactions(
  cliTx: CLITransaction,
  appTx: AppTransaction,
  appBodyBytesBase64?: string,
): void {
  console.log("=".repeat(80));
  console.log("SIGNDOC COMPARISON DIAGNOSTIC");
  console.log("=".repeat(80));

  // 1. Compare message structure
  console.log("\n📋 MESSAGE COMPARISON:");
  console.log("-".repeat(40));

  const cliMsgCount = cliTx.body.messages.length;
  const appMsgCount = appTx.msgs.length;

  console.log(`CLI message count: ${cliMsgCount}`);
  console.log(`App message count: ${appMsgCount}`);

  if (cliMsgCount !== appMsgCount) {
    console.log("❌ MESSAGE COUNT MISMATCH!");
  } else {
    console.log("✅ Message count matches");
  }

  // Compare each message
  for (let i = 0; i < Math.max(cliMsgCount, appMsgCount); i++) {
    console.log(`\n  Message ${i}:`);

    const cliMsg = cliTx.body.messages[i];
    const appMsg = appTx.msgs[i];

    if (cliMsg) {
      console.log(`    CLI typeUrl: ${cliMsg["@type"]}`);
      console.log(`    CLI value: ${JSON.stringify(cliMsg, null, 2).substring(0, 200)}...`);
    }

    if (appMsg) {
      console.log(`    App typeUrl: ${appMsg.typeUrl}`);
      console.log(`    App value: ${JSON.stringify(appMsg.value, null, 2).substring(0, 200)}...`);
    }

    if (cliMsg && appMsg) {
      // Convert CLI @type to typeUrl format
      const cliTypeUrl = cliMsg["@type"];
      if (cliTypeUrl === appMsg.typeUrl) {
        console.log("    ✅ typeUrl matches");
      } else {
        console.log("    ❌ typeUrl MISMATCH!");
      }
    }
  }

  // 2. Compare fee structure
  console.log("\n💰 FEE COMPARISON:");
  console.log("-".repeat(40));

  const cliFee = cliTx.auth_info.fee;
  const appFee = appTx.fee;

  console.log(`CLI gas: ${cliFee.gas_limit}`);
  console.log(`App gas: ${appFee.gas}`);

  if (cliFee.gas_limit === appFee.gas) {
    console.log("✅ Gas matches");
  } else {
    console.log("❌ GAS MISMATCH!");
  }

  console.log(`CLI fee amount: ${JSON.stringify(cliFee.amount)}`);
  console.log(`App fee amount: ${JSON.stringify(appFee.amount)}`);

  const feeMatch = JSON.stringify(cliFee.amount) === JSON.stringify(appFee.amount);
  if (feeMatch) {
    console.log("✅ Fee amount matches");
  } else {
    console.log("❌ FEE AMOUNT MISMATCH!");
  }

  // 3. Compare memo
  console.log("\n📝 MEMO COMPARISON:");
  console.log("-".repeat(40));

  console.log(`CLI memo: "${cliTx.body.memo}"`);
  console.log(`App memo: "${appTx.memo}"`);

  if (cliTx.body.memo === appTx.memo) {
    console.log("✅ Memo matches");
  } else {
    console.log("❌ MEMO MISMATCH!");
  }

  // 4. If we have bodyBytes, decode and compare
  if (appBodyBytesBase64) {
    console.log("\n🔐 BODY BYTES ANALYSIS:");
    console.log("-".repeat(40));

    try {
      const decodedBody = decodeBodyBytes(appBodyBytesBase64);
      console.log("Decoded TxBody from app bodyBytes:");
      console.log(`  - messages count: ${decodedBody.messages.length}`);
      console.log(`  - memo: "${decodedBody.memo}"`);
      console.log(`  - timeoutHeight: ${decodedBody.timeoutHeight.toString()}`);
      console.log(`  - extensionOptions: ${decodedBody.extensionOptions.length}`);

      decodedBody.messages.forEach((msg, i) => {
        console.log(`  Message ${i}:`);
        console.log(`    - typeUrl: ${msg.typeUrl}`);
        console.log(`    - value (hex): ${toHex(msg.value).substring(0, 60)}...`);
      });
    } catch (e) {
      console.log("Failed to decode bodyBytes:", e);
    }
  }

  // 5. Generate Amino SignDoc for comparison
  console.log("\n📜 AMINO SIGNDOC GENERATION:");
  console.log("-".repeat(40));

  const aminoTypes = new AminoTypes({
    ...createDefaultAminoConverters(),
    ...createWasmAminoConverters(),
  });

  try {
    // Convert app msgs to Amino
    const aminoMsgs: AminoMsg[] = appTx.msgs.map((msg) => aminoTypes.toAmino(msg));

    console.log("Amino messages:");
    aminoMsgs.forEach((aminoMsg, i) => {
      console.log(`  Message ${i}:`);
      console.log(`    - type: ${aminoMsg.type}`);
      console.log(`    - value: ${JSON.stringify(aminoMsg.value)}`);
    });

    // Create SignDoc
    const signDoc = makeSignDoc(
      aminoMsgs,
      { amount: appTx.fee.amount, gas: appTx.fee.gas },
      appTx.chainId,
      appTx.memo,
      String(appTx.accountNumber),
      String(appTx.sequence),
    );

    console.log("\nSignDoc (canonical JSON):");
    const serialized = serializeSignDoc(signDoc);
    const signDocJson = new TextDecoder().decode(serialized);
    console.log(signDocJson);

    // Compute hash
    const hash = sha256(serialized);
    console.log(`\nSignDoc SHA256 hash: ${toBase64(hash)}`);
    console.log(`SignDoc SHA256 hash (hex): ${toHex(hash)}`);
  } catch (e) {
    console.log("Failed to generate Amino SignDoc:", e);
  }

  console.log("\n" + "=".repeat(80));
  console.log("END DIAGNOSTIC");
  console.log("=".repeat(80));
}

// Export for use in other scripts
export type { CLITransaction, AppTransaction };
